# Generated by Django 2.1.2 on 2019-03-24 14:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 14, 41, 21, 276399, tzinfo=utc))),
                ('ppm_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
