# Generated by Django 2.1.2 on 2019-03-24 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190325_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
